name: deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
      # We do install instead of ci due to a bug in npm that doesn't
      # properly handle optional dependencies in the lockfile when doing
      # cross platform installs
      # https://github.com/nearform/the-graphql-workshop/pull/742
      - run: npm install
      - run: npm run build -- --base /the-graphql-workshop/
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
